import { useEffect, useState } from "react";
const itemHive = `Class'/Script/FactoryGame.FGItemDescriptor'`
const recipeHive = `Class'/Script/FactoryGame.FGRecipe'`



// Generated by https://quicktype.io

type dataClass = {
  [key: string]: dataClass | string
}[]

type data = {
  loading: 1
  NativeClass: string
  Classes: dataClass
} | { loading: number }


const database: { [key: string]: data } = {}


let a = 1

function useResource(name: string | undefined): number {

  const [result, setResult] = useState(-1);

  useEffect(() => {
    
    setTimeout(() => {
      setResult(Math.random());
    }, 1000*a + Math.random() * 1000);
    a += 1
  }, [])

  return result
}

export { useResource }