import { Map } from "immutable";
import { TileCoordinates } from "./game";


export const enum TileName {
  Undecided,
  Empty,
  GrassLeft,
  GrassMiddle,
  GrassRight,
  HalfGrassLeft,
  HalfGrassRight,
  lightDirt,
  LightToDarkDirt,
  DarkestDirt,
  LeftDirt,
  MediumDirt,
  RightDirt,
  slightBottomLeftHighlightDirt,
  slightBottomRightHighlightDirt,
  slightTopHighlightDirt,
  slightBottomHighlightDirt,
  leftBottomDirt,
  MiddleBottomDirt,
  RightBottomDirt,
  singleDirt,
  RockTopLeft,
  RockTop,
  RockTopRight,
  RockTopLeftHighlight,
  RockTopRightHighlight,
  StoneTopLeft,
  StoneTop,
  StoneTopRight,
  RockLeft,
  RockDark,
  RockRight,
  RockBottomLeftHighlight,
  RockBottomRightHighlight,
  StoneLeft,
  StoneMiddle,
  StoneRight,
  RockBottomLeft,
  RockBottom,
  RockBottomRight,
  RockForwardsDiagonalHighlight,
  RockBackwardsDiagonalHighlight
}
const blockNameCoordinatesInner: [TileName, null | TileCoordinates][] = [
  [TileName.Undecided, null],
  [TileName.Empty, null],
  [TileName.GrassLeft, { x: 0, y: 0 }],
  [TileName.GrassMiddle, { x: 1, y: 0 }],
  [TileName.GrassRight, { x: 2, y: 0 }],
  [TileName.HalfGrassLeft, { x: 3, y: 0 }],
  [TileName.HalfGrassRight, { x: 4, y: 0 }],
  [TileName.lightDirt, { x: 5, y: 0 }],
  [TileName.LightToDarkDirt, { x: 6, y: 0 }],
  [TileName.DarkestDirt, { x: 7, y: 0 }],
  [TileName.LeftDirt, { x: 0, y: 1 }],
  [TileName.MediumDirt, { x: 1, y: 1 }],
  [TileName.RightDirt, { x: 2, y: 1 }],
  [TileName.slightBottomLeftHighlightDirt, { x: 3, y: 1 }],
  [TileName.slightBottomRightHighlightDirt, { x: 4, y: 1 }],
  [TileName.slightTopHighlightDirt, { x: 5, y: 1 }],
  [TileName.slightBottomHighlightDirt, { x: 6, y: 1 }],
  [TileName.leftBottomDirt, { x: 0, y: 2 }],
  [TileName.MiddleBottomDirt, { x: 1, y: 2 }],
  [TileName.RightBottomDirt, { x: 2, y: 2 }],
  [TileName.singleDirt, { x: 5, y: 2 }],
  [TileName.RockTopLeft, { x: 0, y: 3 }],
  [TileName.RockTop, { x: 1, y: 3 }],
  [TileName.RockTopRight, { x: 2, y: 3 }],
  [TileName.RockTopLeftHighlight, { x: 3, y: 3 }],
  [TileName.RockTopRightHighlight, { x: 4, y: 3 }],
  [TileName.StoneTopLeft, { x: 5, y: 3 }],
  [TileName.StoneTop, { x: 6, y: 3 }],
  [TileName.StoneTopRight, { x: 7, y: 3 }],
  [TileName.RockLeft, { x: 0, y: 4 }],
  [TileName.RockDark, { x: 1, y: 4 }],
  [TileName.RockRight, { x: 2, y: 4 }],
  [TileName.RockBottomLeftHighlight, { x: 3, y: 4 }],
  [TileName.RockBottomRightHighlight, { x: 4, y: 4 }],
  [TileName.StoneLeft, { x: 5, y: 4 }],
  [TileName.StoneMiddle, { x: 6, y: 4 }],
  [TileName.StoneRight, { x: 7, y: 4 }],
  [TileName.RockBottomLeft, { x: 0, y: 5 }],
  [TileName.RockBottom, { x: 1, y: 5 }],
  [TileName.RockBottomRight, { x: 2, y: 5 }],
  [TileName.RockForwardsDiagonalHighlight, { x: 3, y: 5 }],
  [TileName.RockBackwardsDiagonalHighlight, { x: 4, y: 5 }],
];


export const blockNameCoordinates = Map<TileName, TileCoordinates | null>(
  blockNameCoordinatesInner
);
